### ISSUE TITLE
dao test failure

### ISSUE THREAD

**Issue by rlespinasse** [sebastienfr/handsongo#3]
run `make test`

```
=== RUN   TestDAOMongo
--- FAIL: TestDAOMongo (0.01s)
    spirit_dao_mongo_test.go:54: The _id field cannot be changed from {_id: ObjectId('5744d56fe1faac11daad76e5')} to {_id: "WD�o��ڭv�"}.
```

**Comment by sebastienfr** [comment]
Pb corrigé avec ton setup et tearDown ?

**Comment by rlespinasse** [comment]
Tu fais quoi pour faire tourner les tests?

voici mes informations système

``` shell
$ go version
go version go1.5.4 darwin/amd64
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
mongo               3.2                 a55d8a328b43        3 weeks ago         313.1 MB
mongo               latest              a55d8a328b43        3 weeks ago         313.1 MB
$ docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   8b63c77
 Built:        Tue May 10 10:39:20 2016
 OS/Arch:      linux/amd64
```

**Comment by sebastienfr** [comment]
go version go1.5.3 darwin/amd64

Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.6.2
 Git commit:   5604cbe
 Built:        Wed Apr 27 15:27:26 UTC 2016
 OS/Arch:      darwin/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Wed Apr 27 00:34:20 2016
 OS/Arch:      linux/amd64

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
eliocity/goblin     latest              bd4472ff616f        21 hours ago        638.9 MB
sfeir/handsongo     latest              7d999ffc3b20        6 days ago          614.5 MB
<none>              <none>              fb14a3a2e1fd        6 days ago          614.5 MB
<none>              <none>              249b4ac1e18e        6 days ago          638.9 MB
<none>              <none>              0ca8bd504f41        6 days ago          614.5 MB
rabbitmq            3.6-management      0aaf0120f505        8 days ago          175.9 MB
golang              1.5-wheezy          6a1d6adcc9b3        2 weeks ago         599.2 MB
mongo               3.2                 a55d8a328b43        3 weeks ago         313.1 MB
mongo               latest              a55d8a328b43        3 weeks ago         313.1 MB

**Comment by sebastienfr** [comment]
J'ai une erreur sur le make file, l'export mongo n'est pas bon je remonte ça tout a l'heure.
Dans tous les cas j'ai pas ton erreur, pb d'encodage ?

**Comment by sebastienfr** [comment]
Tu pourras me dire si tu as toujours le pb avec la head de develop. @lborie a aussi des pb mais ils m'ont l'air différents, plus un pb linux.

`
=== RUN   TestSpiritHandlerGet
--- PASS: TestSpiritHandlerGet (0.00s)
    handler_test.go:55: Test successfull expected 
         {ObjectIdHex("") Caroni Caroni Velier Trinidad  Molasse rhum 15 2015-01-01 00:00:00 +0000 UTC 8.5 heavy tire taste} 
         is equal to result 
         {ObjectIdHex("") Caroni Caroni Velier Trinidad  Molasse rhum 15 2015-01-01 00:00:00 +0000 UTC 8.5 heavy tire taste}
PASS
ok      github.com/sebastienfr/handsongo/web    0.002s
make[1] : on entre dans le répertoire « /home/bodul/workspace/go-workspace/src/github.com/sebastienfr/handsongo »
/bin/sh: 1: 1: not found
Error response from daemon: Cannot kill container 2: No such container: 2
/bin/sh: 1: 1: not found
Error response from daemon: No such container: 2
make[1]: handsongo-mongo-test : commande introuvable
Makefile:88 : la recette pour la cible « teardownTest » a échouée
make[1]: *** [teardownTest] Erreur 127
make[1] : on quitte le répertoire « /home/bodul/workspace/go-workspace/src/github.com/sebastienfr/handsongo »
Makefile:95 : la recette pour la cible « test » a échouée
make: *** [test] Erreur 2
`

**Comment by lborie** [comment]
Je check ce soir pour ma part.

**Comment by rlespinasse** [comment]
J'ai plus de souci avec un `make test`.
C'est ok pour moi.
