### ISSUE TITLE
Code is not gofmt'd

### ISSUE THREAD

**Issue by peterbourgon** [sebastienfr/handsongo#7]
—

**Comment by sebastienfr** [comment]
My build target does the go fmt of my packages before being executed. It's true that **one** file in mongo vendor in branch step 4 and 5 wasn't go fmt'ed. It's fixed, but I'm not sure it's the responsibility of a library user to format the libraries he is using. Any feedback on such issue happening ?

**Comment by peterbourgon** [comment]
Weird! I filed the issue merely after looking at the source in GitHub, but it looks like GitHub is doing some weird rendering, compressing tabs to an apparent 2 spaces

![weird](https://cloud.githubusercontent.com/assets/114509/15896623/522dcbe0-2d91-11e6-8df0-c4373fac06eb.png)

Mea culpa!
